### ISSUE TITLE
Push to tabbar controller

### ISSUE THREAD

**Issue by HarshPandya136** [antiguab/BATabBarController#52]
![Simulator Screen Shot - iPhone XR - 2019-11-13 at 12 34 24](https://user-images.githubusercontent.com/54573630/68740822-ff8f1800-0611-11ea-8432-c499aaea80cc.png)

Hello **Bryan antiguab**,

whenever I load tabbar without push its work fine but whenever I Push to this tabbar controller this issue happned
I checked and apply all properties but not working

can you please check? 

**Thank you**

**Comment by antiguab** [comment]
looking into this!

**Comment by lucaventura** [comment]
@HarshPandya136  I noticed this as well when setting the window root view controller to the view controller containing the tab bar. This is an interim solution that works in the meantime, add this right after adding the tab bar to your view:

`NSLayoutConstraint.activate([
            tabBar.view.bottomAnchor.constraint(equalTo: self.view.bottomAnchor),
            tabBar.view.trailingAnchor.constraint(equalTo: self.view.trailingAnchor),
            tabBar.view.leadingAnchor.constraint(equalTo: self.view.leadingAnchor)
        ])`

@antiguab There are a few `Unable to simultaneously satisfy constraints` errors logged to the console in the demo project. Could be related. I tried overriding `safeAreaInsetsDidChange` in `BATabBar.swift` and performing the same action as in `layoutSubviews` since the `safeAreaInsets` can sometimes be 0 when accessing them immediately but that didn't do the trick.

**Comment by antiguab** [comment]
@lucaventura which simulator did you use? I'm not seeing those errors in the demo project.

**Comment by antiguab** [comment]
also swift version and ios version you're trying to support

**Comment by antiguab** [comment]
happy to look into this more if you guys can provide some sample code that causes the above.
